import { CircleDollarSign, PackageCheck, Plus, ShoppingBag, Users } from "lucide-react";
import { createCustomerAction, createSalesOrderAction, fulfillSalesOrderAction } from "@/app/actions";
import { EmptyState } from "@/components/empty-state";
import { MetricCard } from "@/components/metric-card";
import { PageHeader } from "@/components/page-header";
import { db } from "@/lib/db";
import { tenantContext } from "@/lib/tenant";
import { formatMoney, formatNumber, safeDate } from "@/lib/utils";

export const metadata = { title: "Sales" };

export default async function SalesPage() {
  const ctx=await tenantContext();
  const [customers,farms,cycles,warehouses,products,orders]=await Promise.all([
    db.customer.findMany({where:{tenantId:ctx.tenantId,active:true},orderBy:{name:"asc"}}),
    db.farm.findMany({where:{tenantId:ctx.tenantId,active:true},orderBy:{name:"asc"}}),
    db.productionCycle.findMany({where:{tenantId:ctx.tenantId},orderBy:{name:"asc"}}),
    db.warehouse.findMany({where:{tenantId:ctx.tenantId,active:true},orderBy:{name:"asc"}}),
    db.product.findMany({where:{tenantId:ctx.tenantId,active:true},orderBy:{name:"asc"}}),
    db.salesOrder.findMany({where:{tenantId:ctx.tenantId},include:{customer:true,farm:true,cycle:true,warehouse:true,items:{include:{product:true}}},orderBy:{orderDate:"desc"},take:100}),
  ]);
  const orderValue=orders.filter(o=>o.status!=="CANCELLED").reduce((s,o)=>s+o.items.reduce((a,i)=>a+Number(i.quantity)*Number(i.unitPrice),0),0);
  const fulfilled=orders.filter(o=>["FULFILLED","INVOICED"].includes(o.status)).length;
  const open=orders.filter(o=>["DRAFT","CONFIRMED"].includes(o.status)).length;
  return <><PageHeader eyebrow="Commercial operations" title="Sales" description="Manage customers, produce orders and fulfil stock while automatically creating production-linked revenue."/>
    <section className="metrics"><MetricCard label="Customers" value={String(customers.length)} hint="Active accounts" icon={<Users size={18}/>}/><MetricCard label="Open orders" value={String(open)} hint="Draft + confirmed" icon={<ShoppingBag size={18}/>}/><MetricCard label="Fulfilled orders" value={String(fulfilled)} hint="Completed deliveries" icon={<PackageCheck size={18}/>}/><MetricCard label="Order value" value={formatMoney(orderValue,ctx.tenant.currency)} hint="Excluding cancelled orders" icon={<CircleDollarSign size={18}/>}/></section>
    <div className="grid-2" style={{marginBottom:20}}>
      <form className="form-card" action={createCustomerAction} style={{margin:0}}><div className="card-head"><h3>Add customer</h3><Plus size={19}/></div><div className="form-grid two"><div className="field span-2"><label>Name</label><input name="name" required/></div><div className="field"><label>Email</label><input name="email" type="email"/></div><div className="field"><label>Phone</label><input name="phone"/></div><div className="field span-2"><label>Address</label><input name="address"/></div></div><div className="form-actions"><button className="button">Add customer</button></div></form>
      <div className="card"><div className="card-head"><h3>Fulfilment behaviour</h3></div><p className="muted" style={{lineHeight:1.75}}>If an order line is linked to an inventory product and warehouse, fulfilment posts a SALE movement to stock. The same action records revenue against the selected farm and production cycle, preserving the link from production to customer.</p></div>
    </div>
    <form className="form-card" action={createSalesOrderAction}><div className="card-head"><div><h3>Create sales order</h3><div className="muted" style={{fontSize:13,marginTop:4}}>Use a product + warehouse when the sale should reduce inventory.</div></div><ShoppingBag size={19}/></div><div className="form-grid"><div className="field"><label>Customer</label><select name="customerId" required defaultValue=""><option value="" disabled>Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Farm</label><select name="farmId" defaultValue=""><option value="">Organization-wide</option>{farms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></div><div className="field"><label>Production cycle</label><select name="cycleId" defaultValue=""><option value="">Not allocated</option>{cycles.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Source warehouse</label><select name="warehouseId" defaultValue=""><option value="">No inventory fulfilment</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></div><div className="field"><label>Product</label><select name="productId" defaultValue=""><option value="">Uncatalogued product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="field"><label>Description</label><input name="description" required placeholder="Premium grade tomatoes"/></div><div className="field"><label>Quantity</label><input name="quantity" type="number" required min="0.001" step="0.001"/></div><div className="field"><label>Unit</label><input name="unit" required placeholder="kg / tonne / crate"/></div><div className="field"><label>Unit price</label><input name="unitPrice" type="number" required min="0" step="0.01"/></div><div className="field"><label>Order date</label><input name="orderDate" type="date"/></div><div className="field"><label>Delivery date</label><input name="deliveryDate" type="date"/></div><div className="field"><label>Status</label><select name="status" defaultValue="CONFIRMED"><option>DRAFT</option><option>CONFIRMED</option></select></div><div className="field span-2"><label>Notes</label><input name="notes"/></div></div><div className="form-actions"><button className="button" disabled={!customers.length}>Create order</button></div></form>
    {orders.length?<div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Item</th><th>Farm / cycle</th><th>Value</th><th>Status</th><th></th></tr></thead><tbody>{orders.map(o=>{const total=o.items.reduce((s,i)=>s+Number(i.quantity)*Number(i.unitPrice),0);const item=o.items[0];return <tr key={o.id}><td><b>{o.orderNo}</b><div className="muted" style={{fontSize:12}}>{safeDate(o.orderDate)}</div></td><td>{o.customer.name}</td><td>{item?.product?.name||item?.description||"—"}<div className="muted" style={{fontSize:12}}>{item?`${formatNumber(item.quantity,3)} ${item.unit}`:""}</div></td><td>{o.farm?.name||"Organization"}<div className="muted" style={{fontSize:12}}>{o.cycle?.name||""}</div></td><td>{formatMoney(total,ctx.tenant.currency)}</td><td><span className={`status ${o.status==="CANCELLED"?"warn":o.status==="CONFIRMED"?"neutral":""}`}>{o.status}</span></td><td>{["DRAFT","CONFIRMED"].includes(o.status)?<form action={fulfillSalesOrderAction}><input type="hidden" name="id" value={o.id}/><button className="button secondary small">Fulfil</button></form>:null}</td></tr>})}</tbody></table></div>:<div className="card"><EmptyState title="No sales orders" text="Add a customer and create the first produce or livestock sale."/></div>}
  </>;
}
