import { ArrowDownToLine, Boxes, Plus, Warehouse as WarehouseIcon } from "lucide-react";
import { createProductAction, createWarehouseAction, postInventoryAction } from "@/app/actions";
import { EmptyState } from "@/components/empty-state";
import { MetricCard } from "@/components/metric-card";
import { PageHeader } from "@/components/page-header";
import { db } from "@/lib/db";
import { stockPositions } from "@/lib/ledger";
import { tenantContext } from "@/lib/tenant";
import { formatMoney, formatNumber, safeDate } from "@/lib/utils";
import { ActionForm } from "@/components/action-form";

export const metadata = { title: "Inventory" };

export default async function InventoryPage() {
  const ctx = await tenantContext("inventory.view");
  const [farms, warehouses, products, cycles, txns, positions, valuationRows] = await Promise.all([
    db.farm.findMany({where:{tenantId:ctx.tenantId,active:true,...ctx.scope.farms},orderBy:{name:"asc"}}),
    db.warehouse.findMany({where:{tenantId:ctx.tenantId,active:true,...ctx.scope.byFarm},include:{farm:true},orderBy:{name:"asc"}}),
    db.product.findMany({where:{tenantId:ctx.tenantId,active:true},orderBy:{name:"asc"}}),
    db.productionCycle.findMany({where:{tenantId:ctx.tenantId,...ctx.scope.byFarm,status:{in:["PLANNED","ACTIVE","PAUSED"]}},orderBy:{name:"asc"}}),
    db.inventoryTransaction.findMany({where:{tenantId:ctx.tenantId,...ctx.scope.via("warehouse")},include:{product:true,warehouse:true,cycle:true},orderBy:{occurredAt:"desc"},take:100}),
    stockPositions(ctx.tenantId, db, ctx.farmScope),
    // Weighted inbound cost per product, used to value what is on hand.
    db.inventoryTransaction.groupBy({by:["productId"],where:{tenantId:ctx.tenantId,...ctx.scope.via("warehouse"),type:{in:["OPENING","PURCHASE","RECEIPT","PRODUCTION","ADJUSTMENT_IN","RETURN"]},unitCost:{not:null}},_sum:{quantity:true},_avg:{unitCost:true}}),
  ]);
  const stock = positions.byProduct;
  const avgCost = new Map(valuationRows.map(r=>[r.productId,Number(r._avg.unitCost||0)]));
  const value = new Map(products.map(p=>[p.id,(stock.get(p.id)||0)*(avgCost.get(p.id)||Number(p.standardCost||0))]));
  const lowStock = products.filter(p=>p.reorderLevel!=null && (stock.get(p.id)||0)<=Number(p.reorderLevel)).length;
  const totalValue = [...value.values()].reduce((a,b)=>a+b,0);
  return <><PageHeader eyebrow="Stock control" title="Inventory" description="A ledger-based view of inputs, feed, chemicals, spares and harvested stock."/>
    <section className="metrics"><MetricCard label="Products" value={String(products.length)} hint={`${lowStock} at/below reorder`} icon={<Boxes size={18}/>}/><MetricCard label="Warehouses" value={String(warehouses.length)} hint="Active stock locations" icon={<WarehouseIcon size={18}/>}/><MetricCard label="Estimated stock value" value={formatMoney(totalValue,ctx.tenant.currency)} hint="Based on ledger unit costs" icon={<ArrowDownToLine size={18}/>}/><MetricCard label="Transactions" value={String(txns.length)} hint="Latest 100 shown below" icon={<Plus size={18}/>}/></section>
    <div className="grid-2" style={{marginBottom:20}}><ActionForm className="form-card" action={createWarehouseAction} style={{margin:0}}><div className="card-head"><h3>Add warehouse</h3><WarehouseIcon size={19}/></div><div className="form-grid two"><div className="field"><label>Name</label><input name="name" required placeholder="Central Store"/></div><div className="field"><label>Farm (optional)</label><select name="farmId" defaultValue="">{ctx.scope.limited ? null : <option value="">Organization-wide</option>}{farms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></div></div><div className="form-actions"><button className="button">Create warehouse</button></div></ActionForm>
      <ActionForm className="form-card" action={createProductAction} style={{margin:0}}><div className="card-head"><h3>Add product</h3><Boxes size={19}/></div><div className="form-grid two"><div className="field"><label>Name</label><input name="name" required placeholder="NPK 15-15-15"/></div><div className="field"><label>SKU</label><input name="sku"/></div><div className="field"><label>Category</label><input name="category" required placeholder="Fertilizer"/></div><div className="field"><label>Unit</label><input name="unit" required placeholder="bag"/></div><div className="field"><label>Reorder level</label><input name="reorderLevel" type="number" min="0" step="0.001"/></div><div className="field"><label>Standard cost</label><input name="standardCost" type="number" min="0" step="0.01"/></div><div className="field span-2"><label>Selling price (used on sales &amp; invoices)</label><input name="sellingPrice" type="number" min="0" step="0.01"/></div></div><div className="form-actions"><button className="button">Create product</button></div></ActionForm></div>
    <ActionForm className="form-card" action={postInventoryAction}><div className="card-head"><div><h3>Post stock movement</h3><div className="muted" style={{fontSize:13,marginTop:4}}>Stock is calculated from immutable ledger movements rather than mutable balances.</div></div></div><div className="form-grid"><div className="field"><label>Warehouse</label><select name="warehouseId" required defaultValue=""><option value="" disabled>Select warehouse</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></div><div className="field"><label>Product</label><select name="productId" required defaultValue=""><option value="" disabled>Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="field"><label>Movement</label><select name="type" defaultValue="RECEIPT"><option>RECEIPT</option><option>ISSUE</option><option>ADJUSTMENT_IN</option><option>ADJUSTMENT_OUT</option></select></div><div className="field"><label>Quantity</label><input name="quantity" required type="number" min="0.001" step="0.001"/></div><div className="field"><label>Unit cost</label><input name="unitCost" type="number" min="0" step="0.0001"/></div><div className="field"><label>Lot / batch</label><input name="lotNumber"/></div><div className="field"><label>Production cycle</label><select name="cycleId" defaultValue=""><option value="">Not allocated</option>{cycles.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field span-2"><label>Reference</label><input name="reference" placeholder="PO, GRN, work order..."/></div></div><div className="form-actions"><button className="button" disabled={!warehouses.length||!products.length}>Post transaction</button></div></ActionForm>
    {products.length ? <div className="card" style={{marginBottom:20}}><div className="card-head"><h2>Stock position</h2></div><div className="table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>On hand</th><th>By store</th><th>Reorder</th><th>Selling price</th><th>Est. value</th><th>Status</th></tr></thead><tbody>{products.map(p=>{const on=stock.get(p.id)||0; const low=p.reorderLevel!=null&&on<=Number(p.reorderLevel); return <tr key={p.id}><td><b>{p.name}</b><div className="muted" style={{fontSize:12}}>{p.sku||"No SKU"}</div></td><td>{p.category}</td><td>{formatNumber(on,3)} {p.unit}</td><td className="sub">{warehouses.map(w=>[w.name,positions.byLocation.get(`${w.id}:${p.id}`)||0] as const).filter(([,q])=>q).map(([n,q])=>`${n}: ${formatNumber(q,2)}`).join(" · ")||"—"}</td><td>{p.reorderLevel?formatNumber(p.reorderLevel,3):"—"}</td><td>{p.sellingPrice?formatMoney(p.sellingPrice,ctx.tenant.currency):"—"}</td><td>{formatMoney(value.get(p.id)||0,ctx.tenant.currency)}</td><td><span className={`status ${low?"warn":""}`}>{low?"REORDER":"OK"}</span></td></tr>})}</tbody></table></div></div> : <div className="card"><EmptyState title="No inventory yet" text="Create a warehouse and product, then post your first stock receipt."/></div>}
    {txns.length ? <div className="card"><div className="card-head"><h2>Recent movements</h2></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Movement</th><th>Product</th><th>Warehouse</th><th>Quantity</th><th>Cycle / reference</th></tr></thead><tbody>{txns.map(t=><tr key={t.id}><td>{safeDate(t.occurredAt)}</td><td><span className={`status ${["ISSUE","ADJUSTMENT_OUT","WASTE"].includes(t.type)?"warn":"neutral"}`}>{t.type.replaceAll("_"," ")}</span></td><td>{t.product.name}</td><td>{t.warehouse.name}</td><td>{formatNumber(t.quantity,3)} {t.product.unit}</td><td>{t.cycle?.name||"—"}<div className="muted" style={{fontSize:12}}>{t.reference||""}</div></td></tr>)}</tbody></table></div></div>:null}
  </>;
}
