import { Gauge, Plus, Tractor, Wrench } from "lucide-react";
import { createEquipmentAction, createEquipmentLogAction } from "@/app/actions";
import { EmptyState } from "@/components/empty-state";
import { MetricCard } from "@/components/metric-card";
import { PageHeader } from "@/components/page-header";
import { db } from "@/lib/db";
import { tenantContext } from "@/lib/tenant";
import { formatMoney, formatNumber, safeDate } from "@/lib/utils";
import { ActionForm } from "@/components/action-form";

export const metadata = { title: "Equipment" };

export default async function EquipmentPage() {
  const ctx=await tenantContext("equipment.view");
  const [farms,cycles,equipment,logs]=await Promise.all([
    db.farm.findMany({where:{tenantId:ctx.tenantId,active:true,...ctx.scope.farms},orderBy:{name:"asc"}}),
    db.productionCycle.findMany({where:{tenantId:ctx.tenantId,...ctx.scope.byFarm,status:{in:["PLANNED","ACTIVE","PAUSED"]}},orderBy:{name:"asc"}}),
    db.equipment.findMany({where:{tenantId:ctx.tenantId,...ctx.scope.byFarm},include:{farm:true},orderBy:{name:"asc"}}),
    db.equipmentLog.findMany({where:{tenantId:ctx.tenantId,...ctx.scope.byFarm},include:{equipment:true,farm:true,cycle:true},orderBy:{logDate:"desc"},take:120}),
  ]);
  const serviceDue=equipment.filter(e=>e.nextServiceAt!=null&&e.meterReading!=null&&Number(e.meterReading)>=Number(e.nextServiceAt)).length;
  const value=equipment.reduce((s,e)=>s+Number(e.purchaseValue||0),0);
  const runningCost=logs.reduce((s,l)=>s+Number(l.cost||0),0);
  return <><PageHeader eyebrow="Asset operations" title="Equipment" description="Track tractors, vehicles, pumps, generators and implements with usage and service thresholds."/>
    <section className="metrics"><MetricCard label="Assets" value={String(equipment.length)} hint="Registered equipment" icon={<Tractor size={18}/>}/><MetricCard label="Available" value={String(equipment.filter(e=>e.status==="AVAILABLE").length)} hint="Ready for work" icon={<Gauge size={18}/>}/><MetricCard label="Service due" value={String(serviceDue)} hint="Meter threshold reached" icon={<Wrench size={18}/>}/><MetricCard label="Operating cost" value={formatMoney(runningCost,ctx.tenant.currency)} hint={`Purchase value ${formatMoney(value,ctx.tenant.currency)}`} icon={<Tractor size={18}/>}/></section>
    <ActionForm className="form-card" action={createEquipmentAction}><div className="card-head"><h3>Register equipment</h3><Plus size={20}/></div><div className="form-grid"><div className="field"><label>Name</label><input name="name" required placeholder="John Deere 5075E"/></div><div className="field"><label>Code</label><input name="code" placeholder="TR-04"/></div><div className="field"><label>Category</label><input name="category" required placeholder="Tractor"/></div><div className="field"><label>Farm</label><select name="farmId" defaultValue="">{ctx.scope.limited ? null : <option value="">Shared / central</option>}{farms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></div><div className="field"><label>Status</label><select name="status" defaultValue="AVAILABLE"><option>AVAILABLE</option><option>IN_USE</option><option>MAINTENANCE</option><option>OUT_OF_SERVICE</option></select></div><div className="field"><label>Purchase date</label><input name="purchaseDate" type="date"/></div><div className="field"><label>Purchase value</label><input name="purchaseValue" type="number" min="0" step="0.01"/></div><div className="field"><label>Meter unit</label><input name="meterUnit" placeholder="hours / km"/></div><div className="field"><label>Current meter</label><input name="meterReading" type="number" min="0" step="0.01"/></div><div className="field"><label>Next service at</label><input name="nextServiceAt" type="number" min="0" step="0.01"/></div></div><div className="form-actions"><button className="button">Register equipment</button></div></ActionForm>
    <ActionForm className="form-card" action={createEquipmentLogAction}><div className="card-head"><div><h3>Log usage, fuel or maintenance</h3><div className="muted" style={{fontSize:13,marginTop:4}}>Cycle-linked equipment cost flows into production profitability.</div></div><Wrench size={20}/></div><div className="form-grid"><div className="field"><label>Equipment</label><select name="equipmentId" required defaultValue=""><option value="" disabled>Select asset</option>{equipment.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></div><div className="field"><label>Log type</label><select name="type" defaultValue="USAGE"><option>USAGE</option><option>FUEL</option><option>MAINTENANCE</option><option>BREAKDOWN</option><option>INSPECTION</option></select></div><div className="field"><label>Farm</label><select name="farmId" defaultValue=""><option value="">Use asset farm</option>{farms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></div><div className="field"><label>Production cycle</label><select name="cycleId" defaultValue=""><option value="">Not allocated</option>{cycles.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Date</label><input name="logDate" type="date"/></div><div className="field"><label>Usage hours</label><input name="hours" type="number" min="0" step="0.01"/></div><div className="field"><label>Fuel (L)</label><input name="fuelLiters" type="number" min="0" step="0.001"/></div><div className="field"><label>Cost</label><input name="cost" type="number" min="0" step="0.01"/></div><div className="field"><label>Meter reading</label><input name="meterReading" type="number" min="0" step="0.01"/></div><div className="field span-2"><label>Notes</label><input name="notes"/></div></div><div className="form-actions"><button className="button" disabled={!equipment.length}>Save equipment log</button></div></ActionForm>
    {equipment.length?<div className="table-wrap" style={{marginBottom:20}}><table><thead><tr><th>Asset</th><th>Category</th><th>Location</th><th>Meter</th><th>Next service</th><th>Purchased</th><th>Status</th></tr></thead><tbody>{equipment.map(e=>{const due=e.nextServiceAt!=null&&e.meterReading!=null&&Number(e.meterReading)>=Number(e.nextServiceAt);return <tr key={e.id}><td><b>{e.name}</b><div className="muted" style={{fontSize:12}}>{e.code||"No code"}</div></td><td>{e.category}</td><td>{e.farm?.name||"Shared"}</td><td>{e.meterReading?`${formatNumber(e.meterReading)} ${e.meterUnit||""}`:"—"}</td><td>{e.nextServiceAt?`${formatNumber(e.nextServiceAt)} ${e.meterUnit||""}`:"—"}{due?<div className="status warn" style={{marginTop:4}}>DUE</div>:null}</td><td>{safeDate(e.purchaseDate)}</td><td><span className={`status ${e.status!=="AVAILABLE"?"neutral":""}`}>{e.status.replaceAll("_"," ")}</span></td></tr>})}</tbody></table></div>:<div className="card" style={{marginBottom:20}}><EmptyState title="No equipment" text="Register machinery and assets above."/></div>}
    {logs.length?<div className="card"><div className="card-head"><h2>Recent equipment logs</h2></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Asset</th><th>Type</th><th>Farm / cycle</th><th>Hours / fuel</th><th>Cost</th></tr></thead><tbody>{logs.map(l=><tr key={l.id}><td>{safeDate(l.logDate)}</td><td><b>{l.equipment.name}</b></td><td>{l.type}</td><td>{l.farm?.name||"Shared"}<div className="muted" style={{fontSize:12}}>{l.cycle?.name||""}</div></td><td>{l.hours?`${formatNumber(l.hours,2)} h`:""}{l.hours&&l.fuelLiters?" · ":""}{l.fuelLiters?`${formatNumber(l.fuelLiters,2)} L`:""}</td><td>{l.cost?formatMoney(l.cost,ctx.tenant.currency):"—"}</td></tr>)}</tbody></table></div></div>:null}
  </>;
}
