import { CircleDollarSign, Plus, WalletCards } from "lucide-react";
import { createExpenseAction, createRevenueAction } from "@/app/actions";
import { EmptyState } from "@/components/empty-state";
import { MetricCard } from "@/components/metric-card";
import { PageHeader } from "@/components/page-header";
import { db } from "@/lib/db";
import { tenantContext } from "@/lib/tenant";
import { formatMoney, safeDate } from "@/lib/utils";

export const metadata = { title: "Finance" };

export default async function FinancePage() {
  const ctx = await tenantContext();
  const [farms,cycles,expenses,revenues] = await Promise.all([
    db.farm.findMany({where:{tenantId:ctx.tenantId,active:true},orderBy:{name:"asc"}}),
    db.productionCycle.findMany({where:{tenantId:ctx.tenantId},orderBy:{name:"asc"}}),
    db.expense.findMany({where:{tenantId:ctx.tenantId},include:{farm:true,cycle:true},orderBy:{incurredAt:"desc"},take:200}),
    db.revenue.findMany({where:{tenantId:ctx.tenantId},include:{farm:true,cycle:true},orderBy:{occurredAt:"desc"},take:200}),
  ]);
  const approved=expenses.filter(e=>["APPROVED","PAID"].includes(e.status)).reduce((s,e)=>s+Number(e.amount),0);
  const draft=expenses.filter(e=>e.status==="DRAFT"||e.status==="SUBMITTED").reduce((s,e)=>s+Number(e.amount),0);
  const revenueTotal=revenues.reduce((s,r)=>s+Number(r.amount),0);
  const byCategory=new Map<string,number>(); expenses.filter(e=>["APPROVED","PAID"].includes(e.status)).forEach(e=>byCategory.set(e.category,(byCategory.get(e.category)||0)+Number(e.amount)));
  return <><PageHeader eyebrow="Farm economics" title="Finance" description="Capture spend at source and attach it to farms and production cycles for true production costing."/>
    <section className="metrics"><MetricCard label="Approved spend" value={formatMoney(approved,ctx.tenant.currency)} hint="Approved + paid expenses" icon={<CircleDollarSign size={18}/>}/><MetricCard label="Pending spend" value={formatMoney(draft,ctx.tenant.currency)} hint="Draft + submitted" icon={<WalletCards size={18}/>}/><MetricCard label="Revenue recorded" value={formatMoney(revenueTotal,ctx.tenant.currency)} hint={`${revenues.length} revenue records`} icon={<CircleDollarSign size={18}/>}/><MetricCard label="Net position" value={formatMoney(revenueTotal-approved,ctx.tenant.currency)} hint="Revenue less approved spend" icon={<CircleDollarSign size={18}/>}/></section>
    <form className="form-card" action={createExpenseAction}><div className="card-head"><div><h3>Record expense</h3><div className="muted" style={{fontSize:13,marginTop:4}}>Directly associate spend with the operation that consumed it.</div></div><Plus size={20}/></div><div className="form-grid"><div className="field"><label>Category</label><input name="category" required placeholder="Labour / Fertilizer / Fuel"/></div><div className="field"><label>Amount ({ctx.tenant.currency})</label><input name="amount" required type="number" min="0.01" step="0.01"/></div><div className="field"><label>Farm</label><select name="farmId" defaultValue=""><option value="">Organization-wide</option>{farms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></div><div className="field"><label>Production cycle</label><select name="cycleId" defaultValue=""><option value="">Not allocated</option>{cycles.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field span-2"><label>Description</label><input name="description" required/></div><div className="field"><label>Vendor / payee</label><input name="vendor"/></div><div className="field"><label>Date</label><input name="incurredAt" type="date"/></div><div className="field"><label>Status</label><select name="status" defaultValue="APPROVED"><option>DRAFT</option><option>SUBMITTED</option><option>APPROVED</option><option>PAID</option></select></div><div className="field span-2"><label>Reference</label><input name="reference"/></div></div><div className="form-actions"><button className="button">Record expense</button></div></form>
    <form className="form-card" action={createRevenueAction}><div className="card-head"><div><h3>Record revenue</h3><div className="muted" style={{fontSize:13,marginTop:4}}>Link sales and other income to the farm or production cycle that generated it.</div></div><Plus size={20}/></div><div className="form-grid"><div className="field"><label>Type</label><select name="type" defaultValue="HARVEST_SALE"><option>HARVEST_SALE</option><option>LIVESTOCK_SALE</option><option>MILK</option><option>EGGS</option><option>FISH_SALE</option><option>SERVICE</option><option>OTHER</option></select></div><div className="field"><label>Amount ({ctx.tenant.currency})</label><input name="amount" required type="number" min="0.01" step="0.01"/></div><div className="field"><label>Farm</label><select name="farmId" defaultValue=""><option value="">Organization-wide</option>{farms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></div><div className="field"><label>Production cycle</label><select name="cycleId" defaultValue=""><option value="">Not allocated</option>{cycles.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field span-2"><label>Description</label><input name="description" required placeholder="Sale of maize harvest lot..."/></div><div className="field"><label>Customer</label><input name="customer"/></div><div className="field"><label>Date</label><input name="occurredAt" type="date"/></div><div className="field span-2"><label>Reference</label><input name="reference"/></div></div><div className="form-actions"><button className="button">Record revenue</button></div></form>
    <div className="grid-2" style={{marginBottom:20}}><div className="card"><div className="card-head"><h2>Spend by category</h2></div>{[...byCategory.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([name,value])=><div className="progress-row" key={name}><div className="progress-label"><span>{name}</span><b>{formatMoney(value,ctx.tenant.currency)}</b></div><div className="progress"><span style={{width:`${approved?Math.max(4,value/approved*100):0}%`}}/></div></div>)}{!byCategory.size&&<EmptyState title="No approved spend" text="Approved farm expenses will be grouped here."/>}</div><div className="card"><div className="card-head"><h2>Costing principle</h2></div><p className="muted" style={{lineHeight:1.75}}>FarmHQ keeps farm and production-cycle links on financial records so you can measure cost per hectare, cost per kilogram, cost per animal, margin by cycle and budget variance without rebuilding allocations in spreadsheets.</p></div></div>
    {expenses.length ? <div className="table-wrap" style={{marginBottom:20}}><table><thead><tr><th>Date</th><th>Description</th><th>Farm / cycle</th><th>Category</th><th>Amount</th><th>Status</th></tr></thead><tbody>{expenses.map(e=><tr key={e.id}><td>{safeDate(e.incurredAt)}</td><td><b>{e.description}</b><div className="muted" style={{fontSize:12}}>{e.vendor||e.reference||""}</div></td><td>{e.farm?.name||"Organization"}<div className="muted" style={{fontSize:12}}>{e.cycle?.name||""}</div></td><td>{e.category}</td><td>{formatMoney(e.amount,ctx.tenant.currency)}</td><td><span className={`status ${e.status==="DRAFT"||e.status==="SUBMITTED"?"neutral":""}`}>{e.status}</span></td></tr>)}</tbody></table></div> : <div className="card" style={{marginBottom:20}}><EmptyState title="No expenses" text="Record direct farm and production costs above."/></div>}
    {revenues.length ? <div className="table-wrap"><table><thead><tr><th>Date</th><th>Description</th><th>Farm / cycle</th><th>Type</th><th>Customer</th><th>Amount</th></tr></thead><tbody>{revenues.map(r=><tr key={r.id}><td>{safeDate(r.occurredAt)}</td><td><b>{r.description}</b><div className="muted" style={{fontSize:12}}>{r.reference||""}</div></td><td>{r.farm?.name||"Organization"}<div className="muted" style={{fontSize:12}}>{r.cycle?.name||""}</div></td><td>{r.type.replaceAll("_"," ")}</td><td>{r.customer||"—"}</td><td>{formatMoney(r.amount,ctx.tenant.currency)}</td></tr>)}</tbody></table></div> : null}
  </>;
}
