import { Beef, Plus } from "lucide-react";
import { createAnimalAction, createAnimalHealthEventAction } from "@/app/actions";
import { EmptyState } from "@/components/empty-state";
import { MetricCard } from "@/components/metric-card";
import { PageHeader } from "@/components/page-header";
import { db } from "@/lib/db";
import { tenantContext } from "@/lib/tenant";
import { safeDate } from "@/lib/utils";
import { ActionForm } from "@/components/action-form";

export const metadata = { title: "Livestock" };

export default async function LivestockPage() {
  const ctx = await tenantContext("livestock.view");
  const [farms, units, animals, healthEvents] = await Promise.all([
    db.farm.findMany({where:{tenantId:ctx.tenantId,active:true},orderBy:{name:"asc"}}),
    db.productionUnit.findMany({where:{tenantId:ctx.tenantId,active:true,type:{in:["BARN","PEN","GRAZING_AREA","OTHER"]}},orderBy:{name:"asc"}}),
    db.animal.findMany({where:{tenantId:ctx.tenantId},include:{farm:true,unit:true},orderBy:{createdAt:"desc"}}),
    db.animalHealthEvent.findMany({where:{tenantId:ctx.tenantId},include:{animal:{include:{farm:true}}},orderBy:{eventDate:"desc"},take:100}),
  ]);
  const active=animals.filter(a=>a.status==="ACTIVE").length;
  const species=new Set(animals.map(a=>a.species.toLowerCase())).size;
  return <><PageHeader eyebrow="Animal operations" title="Livestock" description="Individual animal register with farm, location, breed and lifecycle status."/>
    <section className="metrics"><MetricCard label="Registered animals" value={String(animals.length)} hint="All lifecycle states" icon={<Beef size={18}/>}/><MetricCard label="Active animals" value={String(active)} hint="Currently in operation" icon={<Beef size={18}/>}/><MetricCard label="Species" value={String(species)} hint="Across the organization" icon={<Beef size={18}/>}/><MetricCard label="Livestock farms" value={String(new Set(animals.map(a=>a.farmId)).size)} hint="With registered animals" icon={<Beef size={18}/>}/></section>
    <ActionForm className="form-card" action={createAnimalAction}><div className="card-head"><div><h3>Register animal</h3><div className="muted" style={{fontSize:13,marginTop:4}}>Group/flock workflows share this livestock domain without requiring per-bird records.</div></div><Plus size={20}/></div><div className="form-grid"><div className="field"><label>Farm</label><select name="farmId" required defaultValue=""><option value="" disabled>Select farm</option>{farms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></div><div className="field"><label>Unit / pen</label><select name="unitId" defaultValue=""><option value="">No specific unit</option>{units.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></div><div className="field"><label>Tag / ID</label><input name="tag" required placeholder="COW-0042"/></div><div className="field"><label>Species</label><input name="species" required placeholder="Cattle"/></div><div className="field"><label>Breed</label><input name="breed"/></div><div className="field"><label>Sex</label><select name="sex" defaultValue=""><option value="">Not set</option><option>Male</option><option>Female</option></select></div><div className="field"><label>Birth date</label><input name="birthDate" type="date"/></div><div className="field"><label>Notes</label><input name="notes"/></div></div><div className="form-actions"><button className="button" disabled={!farms.length}>Register animal</button></div></ActionForm>
    <ActionForm className="form-card" action={createAnimalHealthEventAction}><div className="card-head"><div><h3>Record animal event</h3><div className="muted" style={{fontSize:13,marginTop:4}}>Build longitudinal weight, care, breeding and veterinary history for each animal.</div></div><Plus size={20}/></div><div className="form-grid"><div className="field"><label>Animal</label><select name="animalId" required defaultValue=""><option value="" disabled>Select animal</option>{animals.filter(a=>a.status==="ACTIVE").map(a=><option key={a.id} value={a.id}>{a.tag} · {a.species}</option>)}</select></div><div className="field"><label>Event type</label><select name="type" defaultValue="WEIGHT"><option>WEIGHT</option><option>VACCINATION</option><option>TREATMENT</option><option>DEWORMING</option><option>DIAGNOSIS</option><option>BREEDING</option><option>PREGNANCY_CHECK</option><option>BIRTH</option><option>OTHER</option></select></div><div className="field span-2"><label>Title</label><input name="title" required/></div><div className="field"><label>Event date</label><input name="eventDate" type="date"/></div><div className="field"><label>Weight (kg)</label><input name="weightKg" type="number" min="0" step="0.001"/></div><div className="field"><label>Medication</label><input name="medication"/></div><div className="field"><label>Dosage</label><input name="dosage"/></div><div className="field"><label>Veterinarian</label><input name="veterinarian"/></div><div className="field"><label>Next due</label><input name="nextDueAt" type="date"/></div><div className="field span-2"><label>Details</label><input name="details"/></div></div><div className="form-actions"><button className="button" disabled={!animals.length}>Record event</button></div></ActionForm>
    {animals.length ? <div className="table-wrap" style={{marginBottom:20}}><table><thead><tr><th>Tag</th><th>Species / breed</th><th>Farm / unit</th><th>Sex</th><th>Birth date</th><th>Status</th></tr></thead><tbody>{animals.map(a=><tr key={a.id}><td><b>{a.tag}</b></td><td>{a.species}<div className="muted" style={{fontSize:12}}>{a.breed||"Breed not set"}</div></td><td>{a.farm.name}<div className="muted" style={{fontSize:12}}>{a.unit?.name||""}</div></td><td>{a.sex||"—"}</td><td>{safeDate(a.birthDate)}</td><td><span className={`status ${a.status!=="ACTIVE"?"neutral":""}`}>{a.status}</span></td></tr>)}</tbody></table></div> : <div className="card" style={{marginBottom:20}}><EmptyState title="No animals registered" text="Add livestock to start building animal history."/></div>}
    {healthEvents.length?<div className="card"><div className="card-head"><h2>Recent animal events</h2></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Animal</th><th>Event</th><th>Weight</th><th>Care / vet</th><th>Next due</th></tr></thead><tbody>{healthEvents.map(e=><tr key={e.id}><td>{safeDate(e.eventDate)}</td><td><b>{e.animal.tag}</b><div className="muted" style={{fontSize:12}}>{e.animal.farm.name}</div></td><td>{e.title}<div className="muted" style={{fontSize:12}}>{e.type.replaceAll("_"," ")}</div></td><td>{e.weightKg?`${e.weightKg} kg`:"—"}</td><td>{e.medication||e.veterinarian||"—"}<div className="muted" style={{fontSize:12}}>{e.dosage||""}</div></td><td>{safeDate(e.nextDueAt)}</td></tr>)}</tbody></table></div></div>:null}
  </>;
}
