import { FileCheck2, FlaskConical, Link2, ShieldCheck } from "lucide-react";
import { createChemicalApplicationAction, createComplianceRecordAction, createDocumentRecordAction } from "@/app/v03-actions";
import { ComplianceActionsPanel } from "@/components/compliance-actions-panel";
import { EmptyState } from "@/components/empty-state";
import { MetricCard } from "@/components/metric-card";
import { PageHeader } from "@/components/page-header";
import { db } from "@/lib/db";
import { tenantContext } from "@/lib/tenant";
import { formatNumber, safeDate } from "@/lib/utils";
import { ActionForm } from "@/components/action-form";

export const metadata = { title: "Compliance" };

export default async function CompliancePage() {
  const ctx = await tenantContext("production.view");
  const [farms, units, cycles, records, chemicals, documents] = await Promise.all([
    db.farm.findMany({ where: { tenantId: ctx.tenantId, active: true, ...ctx.scope.farms }, orderBy: { name: "asc" } }),
    db.productionUnit.findMany({ where: { tenantId: ctx.tenantId, active: true, ...ctx.scope.byFarm }, orderBy: { name: "asc" } }),
    db.productionCycle.findMany({ where: { tenantId: ctx.tenantId, ...ctx.scope.byFarm }, orderBy: { name: "asc" } }),
    db.complianceRecord.findMany({ where: { tenantId: ctx.tenantId, ...ctx.scope.byFarm }, orderBy: [{ dueAt: "asc" }, { createdAt: "desc" }], take: 100 }),
    db.chemicalApplication.findMany({ where: { tenantId: ctx.tenantId, ...ctx.scope.byFarm }, orderBy: { applicationDate: "desc" }, take: 100 }),
    db.documentRecord.findMany({ where: { tenantId: ctx.tenantId, ...ctx.scope.byFarm }, orderBy: { createdAt: "desc" }, take: 100 }),
  ]);
  const farmNames=new Map(farms.map(f=>[f.id,f.name])), unitNames=new Map(units.map(u=>[u.id,u.name])), cycleNames=new Map(cycles.map(c=>[c.id,c.name]));
  const actionRequired=records.filter(r=>r.status==="ACTION_REQUIRED").length;
  const expiringDocs=documents.filter(d=>d.expiresAt).length;
  const open=records.filter(r=>["OPEN","ACTION_REQUIRED"].includes(r.status)).length;

  return <><PageHeader eyebrow="Assurance & traceability" title="Compliance" description="Maintain audit and inspection records, chemical application logs and evidence documents at tenant, farm and production-cycle level."/>
    <section className="metrics"><MetricCard label="Open records" value={String(open)} hint={String(actionRequired)+" require action"} icon={<ShieldCheck size={18}/>}/><MetricCard label="Chemical applications" value={String(chemicals.length)} hint="Latest 100 records" icon={<FlaskConical size={18}/>}/><MetricCard label="Documents" value={String(documents.length)} hint={String(expiringDocs)+" have expiry dates"} icon={<FileCheck2 size={18}/>}/><MetricCard label="Farms covered" value={String(new Set(records.map(r=>r.farmId).filter(Boolean)).size)} hint="With compliance records" icon={<ShieldCheck size={18}/>}/></section>
    <ComplianceActionsPanel tenantId={ctx.tenantId} farmScope={ctx.farmScope} records={records.map(record=>({id:record.id,title:record.title}))}/>
    <div className="grid-2" style={{marginBottom:20}}>
      <ActionForm className="form-card" action={createComplianceRecordAction} style={{margin:0}}><div className="card-head"><h3>Add compliance record</h3><ShieldCheck size={19}/></div><div className="form-grid two"><div className="field"><label>Farm</label><select name="farmId" defaultValue="">{ctx.scope.limited ? null : <option value="">Organization-wide</option>}{farms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></div><div className="field"><label>Type</label><select name="type" defaultValue="INSPECTION"><option>INSPECTION</option><option>CERTIFICATION</option><option>AUDIT</option><option>INCIDENT</option><option>TRAINING</option><option>OTHER</option></select></div><div className="field span-2"><label>Title</label><input name="title" required/></div><div className="field"><label>Status</label><select name="status" defaultValue="OPEN"><option>OPEN</option><option>COMPLIANT</option><option>ACTION_REQUIRED</option><option>EXPIRED</option><option>CLOSED</option></select></div><div className="field"><label>Authority / standard</label><input name="authority"/></div><div className="field"><label>Reference</label><input name="reference"/></div><div className="field"><label>Due date</label><input name="dueAt" type="date"/></div><div className="field"><label>Completed</label><input name="completedAt" type="date"/></div><div className="field span-2"><label>Notes</label><input name="notes"/></div></div><div className="form-actions"><button className="button">Save record</button></div></ActionForm>
      <ActionForm className="form-card" action={createDocumentRecordAction} style={{margin:0}}><div className="card-head"><div><h3>Register evidence document</h3><div className="muted" style={{fontSize:13,marginTop:4}}>Stores a secure or external file URL now; object storage can replace this later without changing the domain model.</div></div><Link2 size={19}/></div><div className="form-grid two"><div className="field"><label>Farm</label><select name="farmId" defaultValue="">{ctx.scope.limited ? null : <option value="">Organization-wide</option>}{farms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></div><div className="field"><label>Production cycle</label><select name="cycleId" defaultValue=""><option value="">Not cycle-specific</option>{cycles.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Category</label><input name="category" required placeholder="Certificate / SOP / Audit"/></div><div className="field"><label>Expires</label><input name="expiresAt" type="date"/></div><div className="field span-2"><label>Title</label><input name="title" required/></div><div className="field span-2"><label>File URL</label><input name="fileUrl" required type="url" placeholder="https://..."/></div><div className="field span-2"><label>Notes</label><input name="notes"/></div></div><div className="form-actions"><button className="button">Register document</button></div></ActionForm>
    </div>
    <ActionForm className="form-card" action={createChemicalApplicationAction}><div className="card-head"><div><h3>Log chemical application</h3><div className="muted" style={{fontSize:13,marginTop:4}}>Capture product, active ingredient, rate, operator and withdrawal or re-entry constraints.</div></div><FlaskConical size={19}/></div><div className="form-grid"><div className="field"><label>Farm</label><select name="farmId" required defaultValue=""><option value="" disabled>Select farm</option>{farms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></div><div className="field"><label>Field / unit</label><select name="unitId" defaultValue=""><option value="">Farm-wide</option>{units.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></div><div className="field"><label>Production cycle</label><select name="cycleId" defaultValue=""><option value="">Not linked</option>{cycles.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Application date</label><input name="applicationDate" type="date"/></div><div className="field"><label>Product</label><input name="productName" required/></div><div className="field"><label>Active ingredient</label><input name="activeIngredient"/></div><div className="field"><label>Quantity</label><input name="quantity" required type="number" min="0.001" step="0.001"/></div><div className="field"><label>Unit</label><input name="unit" required placeholder="L / kg"/></div><div className="field"><label>Rate / ha</label><input name="ratePerHa" type="number" min="0" step="0.001"/></div><div className="field"><label>Operator</label><input name="operator"/></div><div className="field"><label>PHI (days)</label><input name="phiDays" type="number" min="0"/></div><div className="field"><label>REI (hours)</label><input name="reiHours" type="number" min="0"/></div><div className="field span-2"><label>Weather note</label><input name="weatherNote" placeholder="Dry, low wind, no rain forecast"/></div><div className="field span-2"><label>Notes</label><input name="notes"/></div></div><div className="form-actions"><button className="button" disabled={!farms.length}>Log application</button></div></ActionForm>
    <div className="grid-2" style={{marginBottom:20}}>
      <div className="card"><div className="card-head"><h2>Compliance register</h2></div>{records.length?<div className="table-wrap"><table><thead><tr><th>Record</th><th>Farm</th><th>Due</th><th>Status</th></tr></thead><tbody>{records.slice(0,40).map(r=><tr key={r.id}><td><b>{r.title}</b><div className="muted" style={{fontSize:12}}>{r.type} · {r.authority||"Internal"}</div></td><td>{r.farmId?farmNames.get(r.farmId)||"—":"Organization"}</td><td>{safeDate(r.dueAt)}</td><td><span className={"status "+(r.status==="ACTION_REQUIRED"||r.status==="EXPIRED"?"warn":r.status==="OPEN"?"neutral":"")}>{r.status.replaceAll("_"," ")}</span></td></tr>)}</tbody></table></div>:<EmptyState title="No compliance records" text="Add inspections, certifications and audit obligations above."/>}</div>
      <div className="card"><div className="card-head"><h2>Documents</h2></div>{documents.length?<div className="table-wrap"><table><thead><tr><th>Document</th><th>Context</th><th>Expires</th></tr></thead><tbody>{documents.slice(0,40).map(d=><tr key={d.id}><td><a href={d.fileUrl} target="_blank" rel="noreferrer"><b>{d.title}</b></a><div className="muted" style={{fontSize:12}}>{d.category}</div></td><td>{d.farmId?farmNames.get(d.farmId)||"Farm":"Organization"}<div className="muted" style={{fontSize:12}}>{d.cycleId?cycleNames.get(d.cycleId)||"":""}</div></td><td>{safeDate(d.expiresAt)}</td></tr>)}</tbody></table></div>:<EmptyState title="No documents" text="Register certificates, SOPs and supporting evidence above."/>}</div>
    </div>
    {chemicals.length?<div className="card"><div className="card-head"><h2>Chemical application register</h2></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Product</th><th>Farm / field</th><th>Quantity / rate</th><th>Operator</th><th>PHI / REI</th></tr></thead><tbody>{chemicals.map(c=><tr key={c.id}><td>{safeDate(c.applicationDate)}</td><td><b>{c.productName}</b><div className="muted" style={{fontSize:12}}>{c.activeIngredient||""}</div></td><td>{farmNames.get(c.farmId)||"—"}<div className="muted" style={{fontSize:12}}>{c.unitId?unitNames.get(c.unitId)||"":""}</div></td><td>{formatNumber(c.quantity,3)} {c.unit}<div className="muted" style={{fontSize:12}}>{c.ratePerHa?formatNumber(c.ratePerHa,3)+" / ha":""}</div></td><td>{c.operator||"—"}</td><td>{c.phiDays!=null?String(c.phiDays)+"d PHI":"—"}<div className="muted" style={{fontSize:12}}>{c.reiHours!=null?String(c.reiHours)+"h REI":""}</div></td></tr>)}</tbody></table></div></div>:null}
  </>;
}
